spring:
  redis:
    host: "localhost"
biz:
  cluster-session-hash-key: "Session:key"
  heartbeat: 50s
  port: 1983
  host: "127.0.0.1"
  key-store-location:
  ssl-enable: false
  key-store-password:
  so-backlog: 512
  message-id-prefix: "mid"