spring:
  redis:
    host: localhost
biz:
  cluster-session-hash-key: "Session:key"
  heartbeat: 50s
  port: 1883
  host: "0.0.0.0"
  key-store-location:
  ssl-enable: false
  key-store-password:
  so-backlog: 512
  message-id-prefix: "MQTT:MESSAGEID:"
  retain-message-prefix: "MQTT:RETAIN:"
  topic-prefix: "MQTT:TOPIC:"
  pub-msg-set-prefix: "MQTT:CLIENT:PUBMSG:"
  pub-rel-msg-set-prefix: "MQTT:CLIENT:PUBRELMSG:"
  topic-set-key: "MQTT:ALLTOPIC"
  broker-id: 1
  enable-cluster: true
  enable-topic-sub-pub-secure: false
  enable-inner-cache: true
  enable-share-topic: true
  share-sub-strategy: round
  inner-cache-consistency-key: "MQTTX:CACHE_CONSISTENCY"
