spring:
  redis:
    host: "localhost"
biz:
  cluster-session-hash-key: "Session:key"
  heartbeat: 50s
  port: 1883
  host: "127.0.0.1"
  key-store-location:
  ssl-enable: false
  key-store-password:
  so-backlog: 512
  message-id-prefix: "mid"
  retain-message-prefix: "MQTT:RETAIN:"
  topic-prefix: "MQTT:TOPIC:"
  pub-msg-set-prefix: "MQTT:CLIENT:PUBMSG:"